name: Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Create CS3 files and prepare outputs
        run: |
          mkdir -p outputs
          
          # Find and copy APK files, rename to CS3
          find . -name "*.apk" -path "*/build/outputs/apk/release/*" | while read apk_file; do
            provider_name=$(basename $(dirname $(dirname $(dirname $(dirname $(dirname "$apk_file"))))))
            cp "$apk_file" "outputs/${provider_name}.cs3"
            echo "Created: outputs/${provider_name}.cs3"
          done
          
          # Create plugins.json manually
          cat > outputs/plugins.json << 'EOF'
          [
            {
              "iconUrl": "https://www.google.com/s2/favicons?domain=wv5n.cuevana.biz&sz=64",
              "apiVersion": 1,
              "repositoryUrl": "https://github.com/${{ github.repository }}",
              "fileSize": null,
              "status": 1,
              "language": "es",
              "authors": ["YourName"],
              "tvTypes": ["TvSeries", "Movie"],
              "version": 1,
              "internalName": "CuevanaProvider",
              "description": "Cuevana streaming provider for Spanish content",
              "name": "Cuevana",
              "url": "https://github.com/${{ github.repository }}/releases/latest/download/CuevanaProvider.cs3"
            }
          ]
          EOF
          
          ls -la outputs/

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            outputs/*.cs3
            outputs/plugins.json
          tag_name: "release-${{ github.run_number }}"
          name: "Release ${{ github.run_number }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to builds branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./outputs
          publish_branch: builds
          force_orphan: true
